# Generated by Django 4.0.2 on 2022-02-16 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Available_on',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_on_which_device', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Available_on',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Language_supported',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Language_supported',
            },
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Publishers',
            },
        ),
        migrations.CreateModel(
            name='System_requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=255)),
                ('architecture', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'System_requirements',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('game_profile_pic', models.ImageField(upload_to='')),
                ('size', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('best_of_all_time', models.BooleanField()),
                ('trending', models.BooleanField()),
                ('release_date', models.DateTimeField()),
                ('age_rating', models.IntegerField(default=5)),
                ('price', models.CharField(choices=[('PAID', 'Paid'), ('FREE', 'Free')], max_length=255)),
                ('game_price_if_paid', models.IntegerField(blank=True, null=True)),
                ('available_on', models.ManyToManyField(to='games_api.Available_on')),
                ('category', models.ManyToManyField(to='games_api.Category')),
                ('language_supported', models.ManyToManyField(to='games_api.Language_supported')),
                ('publishers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_api.publishers')),
                ('system_requirements', models.ManyToManyField(to='games_api.System_requirements')),
                ('tags', models.ManyToManyField(to='games_api.Tags')),
            ],
            options={
                'verbose_name_plural': 'Games',
                'ordering': ['-release_date'],
            },
        ),
    ]
