# Generated by Django 4.0.2 on 2022-02-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capabilities', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Capabilities',
            },
        ),
    ]
