# Generated by Django 4.0.2 on 2022-02-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_api', '0002_capabilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number_Of_Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_player', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Number_Of_Players',
            },
        ),
    ]
