# Generated by Django 4.0.2 on 2022-02-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_api', '0003_number_of_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
