# Generated by Django 4.0.2 on 2022-02-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_api', '0004_remove_games_tags_delete_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
