# Generated by Django 4.0.2 on 2022-02-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_api', '0005_alter_games_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='release_date',
            field=models.DateField(),
        ),
    ]
