# Generated by Django 4.0.2 on 2022-02-16 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_api', '0007_games_capabilities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Number_Of_Players',
        ),
    ]
